Info2-lecture: Heapsort algorithm
Perytron/UZH pull request #104
Opened 2023-03-22 13:44 UTC by Twhining

Also added a directory for lecture related stuff

2023-03-22 19:43 UTC, C0DECYCLE commented
Very nice thank you for you contribution! If its ok i will adjust the path so that it matches our patterns bit more.

2023-03-22 19:45 UTC, Twhining commented
of course yea i wasn't sure how to do it.

2023-03-22 20:00 UTC, C0DECYCLE requested changes
Minor thing

2023-03-22 20:00 UTC, C0DECYCLE commented on Informatics II/Lectures/Twihning/heapsort.c
> +int arr[N] = {0,2,7,8,3,9,4,1,6,11,14,12,17};
one minor thing, could you please move this array initialisation line inside the main.

2023-03-22 20:16 UTC, Patertuck requested changes
Amazing code, love this. Just have some minor details that don't change the output for cleaner code. Thanks a lot for your contribution! <3

2023-03-22 20:16 UTC, Patertuck commented on Informatics II/Lectures/Twihning/heapsort.c
> +void heapify(int *A, int i , int k){
I would recommend to keep consistent variable names for things. This variable with the length of the array goes from being called "N" to "p" and "s" in Heap_sort into the "k" here. Just call it all "n" for example; It doesn't change the correctness of the code but is way easier to read and understand.

2023-03-22 20:16 UTC, Patertuck commented on Informatics II/Lectures/Twihning/heapsort.c
> +    r = right(i);
This can be shortened as:
```suggestion
    int l = left(i);
    int r = right(i);
```

2023-03-23 12:34 UTC, C0DECYCLE approved these changes
LGTM!

2023-03-23 12:41 UTC, C0DECYCLE commented
https://www.youtube.com/@CodeAesthetic

2023-03-23 13:03 UTC, merged