Info2-006-02-03: Add solution
Perytron/UZH pull request #111
Opened 2023-04-04 07:45 UTC by paul891112

add .c files

2023-04-04 12:12 UTC, C0DECYCLE commented on Informatics II/006/Task 2/Paul891112 Solution/task2.c
> +int* prepend(int *arr, int v);
Redundant

2023-04-04 12:17 UTC, C0DECYCLE requested changes
Minor changes else LGTM

2023-04-04 12:17 UTC, C0DECYCLE commented on Informatics II/006/Task 2/Paul891112 Solution/task2.c
> +}
potentially problematic when "arr" is released later

2023-04-04 12:17 UTC, C0DECYCLE commented on Informatics II/006/Task 3/Paul891112 Solution/task3.c
> +struct node* reverseLinkedList(struct node* head);
Redundant

2023-04-04 19:23 UTC, Patertuck requested changes
I think the point of task 2 was to use the pointers instead of arrays in the different functions. So not calling the accessing by arr[index] but rather *(arr + index). Correct me if I am wrong :)

2023-04-18 16:09 UTC, C0DECYCLE approved these changes

2023-04-19 04:49 UTC, C0DECYCLE commented
My request LGTM👍 Before merge please also fix the point from @Patertuck

2023-05-09 12:37 UTC, merged